<?php
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\" dir=\"ltr\">\n"; 
echo "<head profile=\"http://gmpg.org/xfn/11\">\n"; 
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n"; 
echo "<title>software blog </title>\n"; 
echo "<meta name=\"generator\" content=\"WordPress 2.2\"/>  \n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "//<![CDATA[\n"; 
echo "try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:\"cf\",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:\"/cdn-cgi/nexp/dokv=88e434a982/\"},atok:\"0456610a00e7e37a3b86a2923fc2a80e\",petok:\"51583d3d2dcaac1cc65094400ad34f7b8ccb7d26-1410079328-1800\",zone:\"template-help.com\",rocket:\"0\",apps:{\"abetterbrowser\":{\"ie\":\"7\"},\"ga_key\":{\"ua\":\"UA-7078796-5\",\"ga_bs\":\"2\"}}}];!function(a,b){a=document.createElement(\"script\"),b=document.getElementsByTagName(\"script\")[0],a.async=!0,a.src=\"//ajax.cloudflare.com/cdn-cgi/nexp/dokv=97fb4d042e/cloudflare.min.js\",b.parentNode.insertBefore(a,b)}()}}catch(e){};\n"; 
echo "//]]>\n"; 
echo "</script>\n"; 
echo "<link rel=\"stylesheet\" href=\"http://osc3.template-help.com/wordpress_16693/wp-content/themes/theme406/style.css\" type=\"text/css\" media=\"screen\"/>\n"; 
echo "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"software blog RSS Feed\" href=\"http://osc3.template-help.com/wordpress_16693/?feed=rss2\"/>\n"; 
echo "<link rel=\"pingback\" href=\"http://osc3.template-help.com/wordpress_16693/xmlrpc.php\"/>\n"; 
echo "<link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"RSD\" href=\"http://osc3.template-help.com/wordpress_16693/xmlrpc.php?rsd\"/>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "/* <![CDATA[ */\n"; 
echo "var _gaq = _gaq || [];\n"; 
echo "_gaq.push(['_setAccount', 'UA-7078796-5']);\n"; 
echo "_gaq.push(['_trackPageview']);\n"; 
echo "\n"; 
echo "(function() {\n"; 
echo "var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n"; 
echo "ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n"; 
echo "var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n"; 
echo "})();\n"; 
echo "\n"; 
echo "(function(b){(function(a){\"__CF\"in b&&\"DJS\"in b.__CF?b.__CF.DJS.push(a):\"addEventListener\"in b?b.addEventListener(\"load\",a,!1):b.attachEvent(\"onload\",a)})(function(){\"FB\"in b&&\"Event\"in FB&&\"subscribe\"in FB.Event&&(FB.Event.subscribe(\"edge.create\",function(a){_gaq.push([\"_trackSocial\",\"facebook\",\"like\",a])}),FB.Event.subscribe(\"edge.remove\",function(a){_gaq.push([\"_trackSocial\",\"facebook\",\"unlike\",a])}),FB.Event.subscribe(\"message.send\",function(a){_gaq.push([\"_trackSocial\",\"facebook\",\"send\",a])}));\"twttr\"in b&&\"events\"in twttr&&\"bind\"in twttr.events&&twttr.events.bind(\"tweet\",function(a){if(a){var b;if(a.target&&a.target.nodeName==\"IFRAME\")a:{if(a=a.target.src){a=a.split(\"#\")[0].match(/[^?=&]+=([^&]*)?/g);b=0;for(var c;c=a[b];++b)if(c.indexOf(\"url\")===0){b=unescape(c.split(\"=\")[1]);break a}}b=void 0}_gaq.push([\"_trackSocial\",\"twitter\",\"tweet\",b])}})})})(window);\n"; 
echo "/* ]]> */\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "<div id=\"main\">\n"; 
echo "<div class=\"top\">\n"; 
echo "<div class=\"bot\">\n"; 
echo " \n"; 
echo "<div id=\"header\">\n"; 
echo "<div id=\"logo\">\n"; 
echo "<h1><a href=\"http://osc3.template-help.com/wordpress_16693/\">ICT ERA</a></h1>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo " \n"; 
echo "<div id=\"body\">  \n"; 
echo "<div id=\"side_bar\" class=\"column\">\n"; 
echo "<div class=\"indent\">\n"; 
echo "<div class=\"widget_style\" id=\"statusbar\">\n"; 
echo "</div>\n"; 
echo "<div id=\"categories\" class=\"widget_style\">\n"; 
echo "<h2>who u r?</h2>\n"; 
echo "<ul>\n"; 
echo "<li><a href=\"parents.html\" title=\"View all posts filed under Development\">parents</a>\n"; 
echo "</li>\n"; 
echo "<li><a href=\"teachers.html\" title=\"View all posts filed under Market research\">teachers</a>\n"; 
echo "</li>\n"; 
echo "<li><a href=\"students.html\" title=\"View all posts filed under Security\">students</a>\n"; 
echo "</li>\n"; 
echo "<li><a href=\"careeradvisors.html\" title=\"View all posts filed under Software licensing\">career advisors</a>\n"; 
echo "</li>\n"; 
echo "\n"; 
echo "</ul>\n"; 
echo "</div>\n"; 
echo "<div class=\"widget_style\" id=\"archives\">\n"; 
echo "<h2>Archives</h2>\n"; 
echo "<ul>\n"; 
echo "<li><a href='http://osc3.template-help.com/wordpress_16693/?m=200710' title='October 2007'>SUCCESSFULL STORIES</a></li>\n"; 
echo "</ul>\n"; 
echo "</div>\n"; 
echo "<div class=\"widget_style\" id=\"recent-comments\">\n"; 
echo "<h2>about us</h2>\n"; 
echo "<ul></ul>\n"; 
echo "</div>\n"; 
echo "<div class=\"widget_style\" id=\"meta\">\n"; 
echo "<h2>OUR CLIENTS</h2>\n"; 
echo "<ul>\n"; 
echo "<li><a href=\"http://www.ibm.com.au/\">IBM</a></li>\n"; 
echo "<li><a href=\"http://www.cisco.com/web/ANZ\">CISCO</a></li>\n"; 
echo "<li><a href=\"http://www.colescareers.com.au/\"><abbr title=\"coles\">COLES</abbr></a></li>\n"; 
echo "<li><a href=\"http://www.wowcareers.com.au/\">WOOLWORTHS</a></li>\n"; 
echo "</ul>\n"; 
echo "</div>\n"; 
echo "<div class=\"widget_style\" id=\"links_with_style\">\n"; 
echo "<ul>\n"; 
echo "<li>\n"; 
echo "<li id=\"linkcat-2\" class=\"linkcat\"><h2>OPPORTUNITIES FOR WOMEN</h2>\n"; 
echo "<ul>\n"; 
echo "<li><a href=\"http://www.alexking.org/\">ICT courses</a></li>\n"; 
echo "<li><a href=\"http://inphotos.org/\">PROVIDERS</a></li>\n"; 
echo "<li><a href=\"http://dougal.gunters.org/\">SCHOLARSHIPS</a></li>\n"; 
echo "<li><a href=\"http://photomatt.net/\">INTERNSHIPS</a></li>\n"; 
echo "<li><a href=\"http://zengun.org/weblog/\">JOBS</a></li>\n"; 
echo "\n"; 
echo "</ul>\n"; 
echo "</li>\n"; 
echo "</li>\n"; 
echo "</ul>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "  <div id=\"content\" class=\"column\">\n"; 
echo "<div class=\"search search1\">\n"; 
echo "<strong>INPUT UR INTERESTS</strong><br/>\n"; 
echo "<form method=\"get\" id=\"searchform\" action=\"http://osc3.template-help.com/wordpress_16693\">\n"; 
echo "<input type=\"text\" class=\"input\" value=\"\" name=\"s\" id=\"s\"/><input class=\"submit\" type=\"image\" src=\"http://osc3.template-help.com/wordpress_16693/wp-content/themes/theme406/images/search.gif\" value=\"submit\"/>\n"; 
echo "</form>\n"; 
echo "</div>\n"; 
echo "<div class=\"indent\">\n"; 
echo " \n"; 
echo " \n"; 
echo "<div class=\"title\">\n"; 
echo "<div class=\"left\">\n"; 
echo "<h3><a href=\"http://osc3.template-help.com/wordpress_16693/?p=4\" rel=\"bookmark\" title=\"Permanent Link to Apache guru praises Vista\">WHY ICT?</a></h3>\n"; 
echo "<span class=\"author\"></span>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo " \n"; 
echo "<div class=\"content_text\">\n"; 
echo "<p> <br/>\n"; 
echo "<br/>\n"; 
echo "Information and Communications Technologies (ICT) education is basically our society’s efforts to teach its current and emerging citizens\n"; 
echo " valuable knowledge and skills around computing and communications devices, software that operates them, applications that run on them and systems that are built with them.</br>\n"; 
echo "ICT is complex and quickly changing, and it is confusing for many people. \n"; 
echo "It is so pervasive in the modern world that everyone has some understanding of it, but those understandings are often wildly divergent. </p>\n"; 
echo "<p></p>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo " \n"; 
echo "<div class=\"comment\"><a href=\"http://osc3.template-help.com/wordpress_16693/?p=4#comments\">read comments</a> (0)</div>\n"; 
echo " \n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo " \n"; 
echo " \n"; 
echo " \n"; 
echo "<div class=\"title\">\n"; 
echo "<div class=\"left\">\n"; 
echo "<h3><a href=\"http://osc3.template-help.com/wordpress_16693/?p=3\" rel=\"bookmark\" title=\"Permanent Link to Powerful Automated Scheduler\">Suggestions</a></h3>\n"; 
echo "<span class=\"author\"></span>\n"; 
echo "</div>\n"; 
echo "<div class=\"right date\"></div>\n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo " \n"; 
echo "<div class=\"content_text\">\n"; 
echo "<p><br/>\n"; 
echo "</p>\n"; 
echo "<div class=\"column\" style=\"width:167px;\">\n"; 
echo "<ul>\n"; 
echo "<li><a href=\"#\">ICT courses </a></li>\n"; 
echo "<li><a href=\"#\">Courses on demand</a></li>\n"; 
echo "<li><a href=\"#\">Institutions offering ICT courses</a></li>\n"; 
echo "\n"; 
echo "</ul></div>\n"; 
echo "<div class=\"column\" style=\"width:140px;\">\n"; 
echo "<ul>\n"; 
echo "<li><a href=\"#\">School level courses</a></li>\n"; 
echo "<li><a href=\"#\">Graduate level courses</a></li>\n"; 
echo "<li><a href=\"#\">PG level courses</a></li>\n"; 
echo "<li><a href=\"#\">FAQ's</a></li>\n"; 
echo "\n"; 
echo "</ul></div>\n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "<p></p>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo " \n"; 
echo "<div class=\"comment\"><a href=\"http://osc3.template-help.com/wordpress_16693/?p=3#comments\">read comments</a> (0)</div>\n"; 
echo " \n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo " \n"; 
echo "<div class=\"navigation\">\n"; 
echo "<div class=\"left\"></div>\n"; 
echo "<div class=\"right\"></div>\n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo "<div id=\"footer\">\n"; 
echo "<div class=\"t\">\n"; 
echo "<div class=\"b\">\n"; 
echo "<div class=\"indent\">\n"; 
echo "software blog is proudly powered by <a href=\"http://www.wordpress.org\" target=\"_blank\">WordPress</a><br/>\n"; 
echo "<a href=\"http://osc3.template-help.com/wordpress_16693/?feed=rss2\">Entries (RSS)</a> and <a href=\"http://osc3.template-help.com/wordpress_16693/?feed=comments-rss2\">Comments (RSS)</a>.<br/>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo " \n"; 
echo "</div>\n"; 
echo "<div class=\"clear\"></div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>